### GET all

GET http://localhost:3001/api/blogs


### GET all with "spec" in title

GET http://localhost:3001/api/blogs?search=omena

### add new blog w/o likes via user2

POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inh5ejJAY29tcGFueS5jb20iLCJpZCI6MiwiaWF0IjoxNzQyNzYyOTMwfQ.r8UCjnNNWTTx1t5EKgxI7yDw4hDmNlQO_qjesmueAQw

{
    "author": "author via REST55",
    "url": "url via REST",
    "title": "spec title67",
    "likes": 2,
    "year": 1995
}

### add new blog with likes via user1

POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyQGNvbXBhbnkuY29tIiwiaWQiOjIsImlhdCI6MTc0Mjc1MDY4M30.qnFzpcdQE4hqL-xCcJgKt2bmsUwV9vipEYV3_zGm3i8

{
    "author": "omenaaaa",
    "url": "url via REST",
    "title": "title via REST",
    "likes": 99
}

### delete 1 blog

DELETE http://localhost:3001/api/blogs/1

### update likes of #2

PUT http://localhost:3001/api/blogs/2
content-type: application/json

{
    "likes": 11
}
