### GET all

GET http://localhost:3001/api/blogs


### GET all with "spec" in title

GET http://localhost:3001/api/blogs?search=spec

### add new blog w/o likes via user2

POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOjEsImlhdCI6MTc0Mjc0MDk0OX0.EHqypy82gXd0j02uQuElXeHsxxKe7HiaWnI1biYruRk

{
    "author": "author via REST",
    "url": "url via REST",
    "title": "spec title"
}

### add new blog with likes via user1

POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOjQsImlhdCI6MTc0MjczOTU4NX0.xDho4rSKOMuri4s4gWXYHP8suDe3VxWQc5Cn_ipz7u4

{
    "author": "author via REST",
    "url": "url via REST",
    "title": "title via REST",
    "likes": 11
}

### delete 1 blog

DELETE http://localhost:3001/api/blogs/1

### update likes of #2

PUT http://localhost:3001/api/blogs/2
content-type: application/json

{
    "likes": 11
}
