### GET all

GET http://localhost:3001/api/users

### add new user #1

POST http://localhost:3001/api/users
content-type: application/json

{
    "name": "dummy user 1",
    "username": "xyz@company.com"
}

### add new user #2

POST http://localhost:3001/api/users
content-type: application/json

{
    "name": "dummy user 2",
    "username": "user2@company.com"
}

### update name of #1

PUT http://localhost:3001/api/users/xyz@company.com
content-type: application/json

{
    "name": "dummy user 1"
}
